type: deployment
image:
  repository: registry.vn/test/full-app
  tag: null
  pullPolicy: IfNotPresent
deployment:
  replicas: 3
  containerPort: 9000
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
  strategy:
    type: RollingUpdate
  securityContext:
    readOnlyRootFilesystem: false
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    runAsUser: 2000
    runAsGroup: 1000
    capabilities:
      drop:
      - ALL
  imagePullSecrets:
  - name: regcred
  envFrom:
  - configMapRef:
      name: multi-apps-test-config
  env:
  - name: APP_MODE
    value: production
  - name: DATABASE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: multi-apps-test-secret
        key: DATABASE_PASSWORD
  - name: API_TOKEN
    valueFrom:
      secretKeyRef:
        name: multi-apps-test-secret
        key: API_TOKEN
  volumes:
  - name: custom-data
    emptyDir: {}
  volumeMounts:
  - name: custom-data
    mountPath: /data
  affinity: {}
serviceAccount:
  create: false
  name: default
service:
  type: ClusterIP
  port: 9000
  targetPort: 9000
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
  - host: full.example.com
    paths:
    - path: /
      pathType: ImplementationSpecific
      servicePort: 9000
localConfig:
  enabled: false
