type: deployment
image:
  repository: registry.vn/ecommerce/order-service
  tag: null
  pullPolicy: IfNotPresent
deployment:
  replicas: 1
  containerPort: 8080
  resources: {}
  strategy:
    type: RollingUpdate
  securityContext:
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    capabilities:
      drop:
      - ALL
  imagePullSecrets:
  - name: regcred
  env:
  - name: LOG_LEVEL
    valueFrom:
      configMapKeyRef:
        name: ecommerce-config
        key: LOG_LEVEL
  - name: DB_HOST
    valueFrom:
      configMapKeyRef:
        name: ecommerce-config
        key: DB_HOST
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: ecommerce-secret
        key: DB_PASSWORD
  - name: REDIS_URL
    valueFrom:
      configMapKeyRef:
        name: ecommerce-config
        key: REDIS_URL
  - name: STRIPE_API_KEY
    valueFrom:
      secretKeyRef:
        name: ecommerce-secret
        key: STRIPE_API_KEY
  volumes:
  - name: tmp
    emptyDir: {}
  volumeMounts:
  - name: tmp
    mountPath: /tmp
  affinity: {}
serviceAccount:
  create: false
  name: default
service: {}
ingress: {}
genConfigMaps: false
